[build]
  command = "mkdir -p public && cp -r index.html admin.html script.js admin.js style.css config.json public/"
  publish = "public"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/config.json"
  status = 200
